language: node_js
node_js: 11.12.0
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.cache"
install:
- yarn --silent
before_deploy:
- yarn run build --prefix-paths
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: public
  on:
    branch: master